<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYSvgK6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYSvgK6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYSvgK6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYSvgK6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXYSvgK6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XYSvgK6',
    'container.build_id' => '924db717',
    'container.build_time' => 1580810851,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYSvgK6');
