<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIRdQG0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIRdQG0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTIRdQG0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTIRdQG0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTIRdQG0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TIRdQG0',
    'container.build_id' => '5e7ead46',
    'container.build_time' => 1581759389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIRdQG0');
